### ISSUE TITLE
maintainer switch

### ISSUE THREAD

**Issue by dirkholzapfel** [Moxide/bamboo_mailjet#8]
Hello @fpalluel,

as you mentioned in an older PR you're not in Elixir so often anymore.
We would like to suggest that our company (https://steadyhq.com) takes over the official bamboo-mailjet-adapter and maintains it. What do you think?

Best, Dirk

**Comment by fpalluel** [comment]
Hello,
Firstly, instead of transferring full ownership, I may add you and anyone you suggest as contributors, if you don't mind.

Regards.

**Comment by dirkholzapfel** [comment]
Perfect. So we would like to start with @manukall and @dirkholzapfel.

**Comment by fpalluel** [comment]
Done. Feel free to contact me if you'd like to add anyone else.
